---
title: "45장 프로미스"
excerpt: "모던 자바스크립트 Deep Dive 45장 프로미스 내용 정리"

categories:
  - js
tags:
  - javascript
toc: true
toc_sticky: true
toc_label: 45장 프로미스
---
<br/>


# 45장 프로미스
ES6에서는 비동기 처리를 위한 또 다른 패턴으로 `프로미스`를 도입했다. 프로미스는 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.

## 40.1 비동기 처리를 위한 콜백 패턴의 단점
### 45.1.1 콜백 헬
```javascript
  // GET 요청을 위한 비동기 함수
  const get = url => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 서버의 응답을 콘솔에 출력한다.
        console.log(JSON.parse(xhr.response));
      } else {
        console.error(`${xhr.status} ${xhr.statusText}`);
      }
    };
  };

  // id가 1인 post를 취득
  get('https://jsonplaceholder.typicode.com/posts/1');

  /*
  {
    userId: 1
    id: 1
    title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit'
    body: 'quia et suscipit\nsuscipit recusandae consequuntur …strum rerum est autem sunt rem eveniet architecto'
  }
  */
```

get 함수는 비동기 함수다. 비동기 함수란 함수 내부에 비동기로 동작하는 코드를 포함한 함수를 말한다.  
비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료ㅗ디지 않았다 해도 기다리지 않고 즉시 종료된다. 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.  
따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.  
get 함수가 비동기 함수인 이유는 get 함수 내부의 onload 이벤트 핸들러가 비동기로 동작하기 때문이다. get 함수를 호출하면 GET 요청을 전송하고 onload 이벤트 핸들러를 등록한다음 undefined를 반환하고 즉시 종료된다.  
즉, 비동기 함수인 get 함수 내부의 onload 이벤트 핸들러는 get 함수가 종료된 이후에 실행된다. 따라서 get 함수의 onload 이벤트 핸들러에서 서버의 응답 결과를 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.  

#### get 함수가 서버의 응답 결과를 반환하도록 수정하기
```javascript
  // GET 요청을 위한 비동기 함수
  const get = url => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 1 서버의 응답을 반환한다.
        return JSON.parse(xhr.response);
      } else {
        console.error(`${xhr.status} ${xhr.statusText}`);
      }
    };
  };

  // 2 id가 1인 post를 취득
  const response = get('https://jsonplaceholder.typicode.com/posts/1');
  console.log(response); // undefined
```
xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문(1)은 get 함수의 반환문이 아니다.  
get 함수는 반환문이 생략되었으므로 암묵적으로 undefined를 반환한다.(2)  
함수의 반환값은 명시적으로 호출한 다음에 캐치할 수 있으므로 onload 이벤트 핸들러를 get 함수가 호출할 수 있다면 이벤트 핸들러의 반환값을 get함수가 캐치하여 다시 반환할 수도 있겠지만 onload 이벤트 핸들러는 get 함수가 호출하지 않기 때문에 그럴 수도 없다.  
따라서 onload 이벤트 핸들러의 반환값은 캐치할 수 없다.


#### 서버의 응답을 상위 스코프의 변수에 할당하기
```javascript
  let todos;

  // GET 요청을 위한 비동기 함수
  const get = url => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
      // 1 서버의 응답을 상위 스코프의 변수에 할당한다.
        todos = JSON.parse(xhr.response);
      } else {
        console.error(`${xhr.status} ${xhr.statusText}`);
      }
    };
  };

  // id가 1인 post를 취득
  get('https://jsonplaceholder.typicode.com/posts/1');
  console.log(todos); // 2 undefined
```
이 또한 기대한 대로 동작하지 않는다.
xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러는 언제나 2의 console.log가 종료한 이후에 호출된다. 따라서 2의 시점에는 아직 변수 todos에 서버의 응답 결과가 할당되기 이전이다.  
다시말해 xhr.onload 이벤트 핸들러에서 서버의 응답을 상위 스코프의 변수에 할당(1)하면 처리 순서가 보장되지 않는다.  
xhr.onload 핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행되는 것이 아니다. xhr.onload 이벤트 핸들러는 load 이벤트가 발생하면 일단 테스크 큐에 저장되어 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.  
따라서 xhr.onload 이벤트 핸들러가 실행되는 시점에는 콜 스택이 빈 상태여야 하므로 2의 console.log는 이미 종료된 이후다. 즉, xhr.onload 이벤트 핸들러에서 상위 스코프의 변수에 서버의 응답 결과를 할당하기 이전에 console.log가 먼저 호출되어 undefined가 출력된다.  


이처럼 비동기 한수는 비동기 처리 결과를 외부에 반환할 수 없거, 상위 스코프의 변수에 할당할 수도 없다.  
따라서 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 이때 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다.
필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면 호출될 콜백 함수를 전달할 수 있다.  
콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생하는데, 이를 `콜백 헬`이라 한다.
```javascript
  // GET 요청을 위한 비동기 함수
  const get = (url, callback) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
      // 서버의 응답을 상위 스코프의 변수에 할당한다.
        callback(JSON.parse(xhr.response));
      } else {
        console.error(`${xhr.status} ${xhr.statusText}`);
      }
    };
  };

  const url = 'https://jsonplaceholder.typicode.com';
  // id가 1인 post를 취득
  get(`${url}/posts/1`, ({userId}) => {
    console.log(userId); // 1
    // post의 userId를 사용하여 user 정보를 취득
    get(`${url}/users/${userId}`, userInfo => {
      console.log(userInfo); // {id: 1, name: 'Leanne Graham', username: 'Bret', email: 'Sincere@april.biz', address: {…}, …}
    });
  });
```
위 예제를 보면 GET 요청을 통해 서버로부터 응답을 취득하고 이 데이터를 사용하여 또다시 GET 요청을 한다. 콜백 헬은 가독성을 나쁘게 하며 실수를 유발하는 원인이 된다. 

```javascript
  // 콜백 헬 전형적 사례
  get(`/step1`, a => {
    get(`/step2/${a}`, b => {
      get(`/step3/${b}`, c => {
        get(`/step2/${c}`, d => {
          console.log(d);
        });  
      });  
    });  
  });
```

### 45.1.2 에러 처리의 한계
비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것이다.
```javascript
  try {
    setTimeout(() => {
      throw new Error('Error!');
    }, 1000)
  } catch (e) {
    // 에러를 캐치하지 못한다
    console.error('캐치한 에러', e);
  }
```
#### 에러를 캐치하지 못한 이유
setTimeout은 비동기 함수이므로 콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료되어 콜 스택에서 제거된다. 이후 타이머가 만료되면 setTimeout 함수의 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비어졌을 때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.  
setTimeout 함수의 콜백 함수가 실행될 때 setTimeout 함수는 이미 콜 스택에서 제거된 상태다. 이것은 setTimeout 함수의 콜백 함수를 호출한 것이 setTimeout 함수가 아니라는 것을 의미한다.
에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸기되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다. 하지만 앞에서 살펴본 바와 같이 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다. 따라서 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

지금까지 살펴본 비동기 처리를 위한 콜백 패턴은 콜백 헬이나 에러 처리가 곤란하다는 문제가 있다. `이를 극복하기위해 ES6에서 프로미스가 도입되었다.`

## 45.2 프로미스의 생성
promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스(promise 객체)를 생성한다.  
promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.
```javascript
  // 프로미스 생성
  const promise = new Promise((resolve, reject) => {
    // promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
    if ( /* 비동기 처리 성공 */) {
      resolve('result');
    } else { /* 비동기 처리 실패 */
      reject('failure reason')
    }
  });
```
 
 ### 앞에서 살펴본 비동기 함수 get을 프로미스로 구현
 ```javascript
  // GET 요청을 위한 비동기 함수
  const promiseGet = url => {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('GET', url);
      xhr.send();

      xhr.onload = () => {
        if (xhr.status === 200) {
          // 성공적으로 응답을 전달받으면 resolve
          resolve(JSON.parse(xhr.response));
        } else {
          // 에러 처리를 위해 reject 함수를 호출한다.
          reject(new Error(xhr.status));
        }
      }
    })
  }
  

  promiseGet('https://jsonplaceholder.typicode.com/posts/1');
```
비동기 함수인 promiseGet은 함수 내부에서 프로미스를 생성하고 반환한다. 비동기 처리는 Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행한다. 만약 비동기 처리가 성공하면 비동기 처리 결과를 resolve 함수에 인수로 전달하면서 호출하고, 비동기 처리가 실패하면 에러를 reject 함수에 인수로 전달하면서 호출한다.

프로미스는 다음과 같이 현대 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 갖는다.
프로미스의 상태 정보 | 의미 | 상태 변경 조건
--|--|--
pending | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태
fulfilled | 비동기 처리가 수행된 상태(성공) | resolve 함수 호출
rejected | 비동기 처리가 수행된 상태(실패) | reject 함수 호출

생성된 직후의 프로미스는 기본적으로 pending 상태다. 이후 비동기 처리가 수행되면 비동기 처리 결과에 따라 다음과 같이 프로미스의 상태가 변경된다.  
- 비동기 처리 성공 : resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경한다.
- 비동기 처리 실패 : reject 함수를 호출해 프로미스를 rejected 상태로 변경한다.  

이처럼 프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정된다.  
<img width="540" alt="image" src="https://user-images.githubusercontent.com/44577555/174729452-08a8b70a-a7fc-4928-8c41-fe524b866728.png">


fulfilled 또는 rejected 상태를 settled 상태라고 한다. settled 상태는 fulfilled 또는 rejected 상태와 상관없이 pending이 아닌 상태로 비동기 처리가 수행된 상태를 말한다.  
프로미스는 pending 상태에서 fulfilled 또는 rejected 상태, 즉 settled 상태로 변화할 수 있다. 하지만 일단 settled 상태가 되면 더는 다른 상태로 변화할 수 없다.
```javascript
  // fulfilled된 프로미스
  const fulfilled = new Promise(resolve => resolve(1));
```

<img width="399" alt="image" src="https://user-images.githubusercontent.com/44577555/174729547-b5db7b5d-9a88-4ac8-88f0-a26eb6ab43b4.png">

비동기 처리가 성공하면 프로미스는 pending에서 fulfilled 상태로 변화한다.  


```javascript
  // rejected된 프로미스
  const rejected = new Promise((-, reject) => reject(new Error(`error occurred`)));
```
<img width="556" alt="image" src="https://user-images.githubusercontent.com/44577555/174729623-6a29ed3a-b3cf-4255-b09c-d99e0f3463c8.png">

비동기 처리가 실패하면 프로미스는 pending에서 rejected 상태로 변화한다. 그리고 비동기 처리 결과인 Error 객체를 값으로 갖는다.  
즉, 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.

## 45.3 프로미스의 후속 처리 메서드
프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야 한다.  
프로미스는 후속 메서드 then, catch, finally를 제공한다.  
프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다. 이때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.  
모든 후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작한다. 프로미스의 후속 처리 메서드는 다음과 같다.

### 45.3.1 Promise.prototype.then
then 함수는 두 개의 콜백 함수를 인수로 받는다.  
- 첫 번째 콜백 함수는 프로미스가 fulfilled 상태(resolve 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
- 두 번째 콜백 함수는 프로미스가 rejected 상태(reject 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.  

즉, 첫 번째 콜백 함수는 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수이며, 두 번째 콜백 함수는 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수다.

```javascript
  //fulfilled
  new Promise(resolve => resolve(`fulfilled`))
    .then(v => console.log(v), e => console.error(e)); // fulfilled

  // rejected
  new Promise((_, reject) => reject(new Error('rejected')))
    .then(v => console.log(v), e => console.error(e)); // Error: rejected
```
then 메서드는 언제나 프로미스를 반환한다. 만약 then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject하여 프로미스를 생성해 반환한다.

### 45.3.2 Promise.prototype.catch
catch 메서드는 한 개의 콜백 함수를 인수로 전달 받는다. catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.
```javascript
  // rejected
  new Promise((_, reject) => reject(new Error('rejected')))
    .catch(e => console.error(e)); // Error: rejected
```
catch 메서드는 then(undefined, onRejected)과 동일하게 동작한다. 따라서 then 메서드와 마찬가지로 언제나 프로미스를 반환한다.

### 45.3.3 Promise.prototype.finally
finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다. finally 메서드의 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다. `finally 메서드는 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다.` finally 메서드도 then/catch 메서드와 마찬가지로 언제나 프로미스를 반환한다.
```javascript
  new Promise((_, reject) => reject(new Error('rejected')))
    .finally(() => console.log('finally')); // finally
```

#### 프로미스로 구현한 비동기 함수 get을 사용해 후속 처리를 구현
```javascript
  const promiseGet = url => {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('GET', url);
      xhr.send();

      xhr.onload = () => {
        if(xhr.status === 200) {
          // 성공적으로 응답을 전달 받으면 resolve 함수를 호출
          resolve(JSON.parse(xhr.response));
        } else {
          // 에러 처리를 위해 reject 함수를 호출한다.
          reject(new Error(xhr.status));
        }
      };
    });
  };

  // promiseGet 함수는 프로미스를 반환한다.
  promiseGet('https://jsonplaceholder.typicode.com/posts/1')
    .then(res => console.log(res))
    .catch(err => console.log(err))
    .finally(() => console.log('Bye!'));
```

<img width="487" alt="image" src="https://user-images.githubusercontent.com/44577555/174737987-94725ae5-134e-499c-8302-42156ee26cfc.png">


## 45.4 프로미스의 에러 처리
비동기 처리 결과에 대한 후속 처리는 프로미스가 제공하는 후속 처리 메서드 then, catch, finally를 사용하여 수행한다. `비동기 처리에서 발생한 에러는 then 메서드의 두 번째 콜백 함수 또는 catch를 사용하여 처리할 수 있다.`

```javascript
  // then
  const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1'

  // 부적절한 url이 지정되었기 때문에 에러가 발생
  promiseGet(wrongUrl).then(
    res => console.log(res),
    err => console.error(err)
  ); // Error: 404
```

```javascript
  // catch
  const wrongUrl = 'https://jsonplaceholder.typicode.com/xxx/1'

  // 부적절한 url이 지정되었기 때문에 에러가 발생
  promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)); // Error: 404
```
catch 메서드를 호출하면 내부적으로 then(undefined, onRejected)을 호출한다. 따라서 위 예제는 내부적으로 다음과 같이 처리된다.
```javascript
  const wrongUrl = 'https://jsonplaceholder.typicode.com/xxx/1'

  // 부적절한 url이 지정되었기 때문에 에러가 발생
  promiseGet(wrongUrl)
  .then(res => console.log(res))
  .then(undefined, err => console.error(err)); // Error: 404
```

catch 메서드를 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러 뿐만 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.
```javascript
  // catch
  promiseGet('https://jsonplaceholder.typicode.com/todos/1')
  .then(res => console.xxx(res))
  .catch(err => console.error(err));
```

또한 then 메서드에서 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성이 좋고 명확하다.  
따라서 에러 처리는 then 메서드에서 하지 말고 catch 메서드에서 하는 것을 권장한다.